FROM ghcr.io/dask/dask

RUN mkdir -p app

COPY src/cesm-2-dashboard/stratus.py /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

CMD ["python","-c","'import" "stratus;" "stratus.get_data_files()'"]