FROM ghcr.io/dask/dask

RUN mkdir -p app

COPY src/cesm-2-dashboard/prepare.sh /usr/bin/prepare.sh
COPY src/cesm-2-dashboard/stratus.py /app
COPY src/cesm-2-dashboard/get_data.py /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && \
    conda install -c conda-forge cartopy

WORKDIR /app

ENTRYPOINT ["tini", "-g", "--", "/usr/bin/prepare.sh"]
