# Reference https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.webapp.name }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ .Values.webapp.name }}
    minReplicas: {{ .Values.webapp.autoscale.minReplicaCount }}
    maxReplicas: {{ .Values.webapp.autoscale.maxReplicaCount }}
    metrics:
    - type: Resource
        resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: {{ .Values.webapp.autoscale.cpuAverageUtilization }}